### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by robotlearning123** [harryzhangOG/Deep-RL-Notes#1]
Hi, thanks for your great notes.
I just found a typo in Chapter 10.1.1. : 
The KL-divergence $D_{KL}(q_i(x_i))||(p(z|x_i)$. 
And the correct should be this: $D_{KL}(q_i(z)||p(z|x_i))$?

**Comment by harryzhangOG** [comment]
thank you so much, Cong! I fixed the typo.
