### ISSUE TITLE
3.7.1 typo

### ISSUE THREAD

**Issue by zhykoties** [harryzhangOG/Deep-RL-Notes#2]
The first equation seems to have its first parenthesis in the wrong place: https://youtu.be/VgdSubQN35g?list=PL_iWQOsE6TfU9DwANRsUZf0YUUJS_ySr0&t=152

**Comment by harryzhangOG** [comment]
yea thank you, it was a very subtle mistake. i updated the tex file and uploaded a corrected pdf too.
