### ISSUE TITLE
Some typos.

### ISSUE THREAD

**Issue by ghost** [harryzhangOG/Deep-RL-Notes#3]
Hi, 

First of all, thanks so much for the notes! They are extremely useful. 

I just wanted to point out a few typos:

1. Last equation of Ch.7 (step size): missing `J(\theta)` after last grad on the denominator. [Link](https://youtu.be/QWnpF0FaKL4?list=PL_iWQOsE6TfU9DwANRsUZf0YUUJS_ySr0&t=874)
2. Algorithm 14 (DDPG), page 34: line 4 should not have a `\max_a` in front of Q (since we are finding the best state-action function by training a NN to learn the best action `\mu_{\theta}`). Also, although this is not a typo per se, I think after the summation in line 6 there should be a `\frac{d \mu_{\theta}}{d \theta}` rather that `\frac{d a}}{d \theta}`, as that "a" in that derivative is the output from the NN above. [Link](https://youtu.be/Q-Qwjz8Zmh0?list=PL_iWQOsE6TfU9DwANRsUZf0YUUJS_ySr0&t=560)
3. Algorithm 5 (Online AC), page 22: line 5 does not have a `\sum_i` as we are updating one value at a time. [Link](https://youtu.be/g4_2IfZqDLI?list=PL_iWQOsE6TfU9DwANRsUZf0YUUJS_ySr0&t=22)

I hope this helps! Thanks!
Javier.

**Comment by harryzhangOG** [comment]
Thank you. These are extremely helpful! I updated the files accordingly.
