### ISSUE TITLE
Typo in Chapter 10 

### ISSUE THREAD

**Issue by robotlearning123** [harryzhangOG/Deep-RL-Notes#4]
Hi Harry, great note! Just found some small typos in chapter 10:

**1. The sigma** (page 60)

> $p(x|z) =  \mathcal{N}(\mu_{nn}(z),\mu_{nn}(z))$

And the correct should be this:

> $p(x|z) = \mathcal{N}(\mu_{nn}(z),\sigma_{nn}(z))$

**2. The theta display** (page 60)

> \[
> theta\leftarrow \argmaxA_\theta\frac{1}{N}\sum_i\mathbb{E}_{z\sim p(z|x_i)}\log p_\theta(x_i)
> \]

**Comment by harryzhangOG** [comment]
fixed, closing this issue. sorry for the delay - just finished up my Master's thesis
